name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v1
      with:
        name: test-results-re-index
        path: /home/runner/work/LOG8371/LOG8371/modules/rank-eval/build/reports/tests/test
    - name: Set up JDK 13.0.2
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.2'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Run Reindex tests with Gradle
      run: ./gradlew :modules:reindex:test -i --tests org.elasticsearch.index.reindex.AsyncBulkByScrollActionTests 
    - name: Run Mapper tests with Gradle
      run: ./gradlew :modules:mapper-extras:test -i --tests org.elasticsearch.index.mapper.RankFeatureFieldMapperTests 
    - name: Run GeoIp tests with Gradle
      run: ./gradlew :modules:ingest-geoip:test -i --tests org.elasticsearch.ingest.geoip.GeoIpProcessorTests.testCity 
    - name: Run Rankeval tests with Gradle
      run: ./gradlew :modules:rank-eval:test -i --tests org.elasticsearch.index.rankeval.DiscountedCumulativeGainTests.testDCGAt
