name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name :  Configure gradle
      run: chmod +x ./gradle.sh
    - name : Setup gradle
      run: source ./gradle.sh
    - name: Grant execute permission for gradlew
      run: chmod +x gradle
    - name: Build with Gradle
      run: gradle :modules:ingest-geoip:test:src:test --tests org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests 
